[tool.black]
line-length = 127
include = '\.pyi?$'
# check = true
# diff = true
# color = true

# https://pypi.org/project/Flake8-pyproject/
[tool.flake8]
max-line-length = 127
max-complexity = 10
# select=E9,F63,F7,F82
exclude = [".git", "__pycache__"]
count = true
exit-zero = true
statistics = true
show-source = true

[tool.pytest.ini_options]
pythonpath = [
  "."
]
markers = ["constructor: construction of objects"]
