# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Python app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install flake8 Flake8-pyproject pytest 
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Code formatting with Black
      uses: psf/black@stable
      with: 
        options: "--check --verbose --diff --color"
        src: "./"
    - name: Lint with flake8
      run: |
          flake8 .
    - name: Test with pytest
      run: |
        pytest
